/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salmah Nansamba
 */
public class PiersCalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form PiersCalculatorUI
     */
    public PiersCalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTabbedPane = new javax.swing.JTabbedPane();
        SI_panel = new javax.swing.JPanel();
        firstname_label = new javax.swing.JLabel();
        firstname_input = new javax.swing.JTextField();
        lastname_label = new javax.swing.JLabel();
        lastname_input = new javax.swing.JTextField();
        gestationalAge_label = new javax.swing.JLabel();
        weeks_input = new javax.swing.JTextField();
        weeks_label = new javax.swing.JLabel();
        days_input = new javax.swing.JTextField();
        days_label = new javax.swing.JLabel();
        dsypnoea_label = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        SpO2_label = new javax.swing.JLabel();
        platelets_label = new javax.swing.JLabel();
        creatinineSI_label = new javax.swing.JLabel();
        ast_label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        probability_label = new javax.swing.JLabel();
        probability_output = new javax.swing.JTextField();
        percentage_label = new javax.swing.JLabel();
        calculate_button = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        SpO2_input = new javax.swing.JTextField();
        platelets_input = new javax.swing.JTextField();
        creatinineSI_input = new javax.swing.JTextField();
        ast_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIERS Calculator\n");

        firstname_label.setText("First Name:");

        lastname_label.setText("Last Name:");

        gestationalAge_label.setText("Gestational age(at delivery, if de novo postpartum pre-eclampsia):");

        weeks_label.setText("weeks");

        days_label.setText("days");

        dsypnoea_label.setText("Did the patient have chest pain or dyspnoea?");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select one--", "Yes", "No" }));

        SpO2_label.setText("SpO2*(use 97% if unknown):");

        platelets_label.setText("Platelets(x10^9/L):");

        creatinineSI_label.setText("Creatinine(micromol/L):");

        ast_label.setText("AST(U/L):");

        probability_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        probability_label.setText("Probability of adverse maternal outcomes:");

        percentage_label.setText("%");

        calculate_button.setText("Calculate");
        calculate_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculate_buttonMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel26.setText("*- Oxygen saturation by pulse oximetry");

        javax.swing.GroupLayout SI_panelLayout = new javax.swing.GroupLayout(SI_panel);
        SI_panel.setLayout(SI_panelLayout);
        SI_panelLayout.setHorizontalGroup(
            SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SI_panelLayout.createSequentialGroup()
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SI_panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SI_panelLayout.createSequentialGroup()
                                .addComponent(lastname_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gestationalAge_label)
                            .addGroup(SI_panelLayout.createSequentialGroup()
                                .addComponent(firstname_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SI_panelLayout.createSequentialGroup()
                                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SI_panelLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(weeks_input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(weeks_label))
                                    .addComponent(dsypnoea_label)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SI_panelLayout.createSequentialGroup()
                                        .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(platelets_label)
                                            .addComponent(SpO2_label)
                                            .addComponent(creatinineSI_label)
                                            .addComponent(ast_label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel26))
                                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpO2_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(SI_panelLayout.createSequentialGroup()
                                        .addComponent(days_input, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(days_label))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(platelets_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(creatinineSI_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ast_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(SI_panelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(probability_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(probability_output, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentage_label))
                    .addGroup(SI_panelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(calculate_button))
                    .addGroup(SI_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        SI_panelLayout.setVerticalGroup(
            SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SI_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname_label)
                    .addComponent(lastname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(gestationalAge_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(days_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(days_label)
                    .addComponent(weeks_label)
                    .addComponent(weeks_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dsypnoea_label)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpO2_label)
                    .addComponent(SpO2_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platelets_label)
                    .addComponent(platelets_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatinineSI_label)
                    .addComponent(creatinineSI_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ast_label)
                    .addComponent(ast_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SI_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(probability_label)
                    .addComponent(probability_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentage_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate_button)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("SI units", SI_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculate_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculate_buttonMouseClicked
        // TODO add your handling code here:
        String weeks = weeks_input.getText();
        int weeks_value = Integer.parseInt(weeks);              
        
        String days = days_input.getText();
        int days_value = Integer.parseInt(days);
//        System.out.println("days = "+days);
        
        String platelets = platelets_input.getText();
        double platelets_value = Double.parseDouble(platelets);
//        System.out.println("Weeks = "+weeks);
        
        String SpO2 = SpO2_input.getText();
        double SpO2_value = Double.parseDouble(SpO2);
        
        String creatinine = creatinineSI_input.getText();
        double creatinineSI_value = Double.parseDouble(creatinine);
        
        String ast = ast_input.getText();
        double ast_value = Double.parseDouble(ast);
        
        PiersEquation equation = new PiersEquation(weeks_value, days_value, true, creatinineSI_value, platelets_value, ast_value, SpO2_value);
        double prob = equation.get_probability();
        System.out.println("Result is ...."+prob);
        
        probability_output.setText(""+prob);
        
        
    }//GEN-LAST:event_calculate_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiersCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiersCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiersCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiersCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiersCalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JPanel SI_panel;
    private javax.swing.JTextField SpO2_input;
    private javax.swing.JLabel SpO2_label;
    private javax.swing.JTextField ast_input;
    private javax.swing.JLabel ast_label;
    private javax.swing.JButton calculate_button;
    private javax.swing.JTextField creatinineSI_input;
    private javax.swing.JLabel creatinineSI_label;
    private javax.swing.JTextField days_input;
    private javax.swing.JLabel days_label;
    private javax.swing.JLabel dsypnoea_label;
    private javax.swing.JTextField firstname_input;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JLabel gestationalAge_label;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastname_input;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JLabel percentage_label;
    private javax.swing.JTextField platelets_input;
    private javax.swing.JLabel platelets_label;
    private javax.swing.JLabel probability_label;
    private javax.swing.JTextField probability_output;
    private javax.swing.JTextField weeks_input;
    private javax.swing.JLabel weeks_label;
    // End of variables declaration//GEN-END:variables
}
